### ISSUE TITLE
NPE when running readBytes with future module 

### ISSUE THREAD

**Issue by 2m** [travisbrown/iteratee#168]
The following ammonite script

```scala
import $ivy.`io.iteratee::iteratee-files:0.8.0`

import scala.concurrent.ExecutionContext.Implicits.global

val fileModule = io.iteratee.modules.future
val fileFuture = io.iteratee.files.future

import cats.implicits._
import fileModule._
import fileFuture._

val res = readBytes(new java.io.File("/dev/urandom")).into(takeI(1))
res.onFailure { case t => t.printStackTrace }
```

prints a following stack trace

```
java.lang.NullPointerException
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transformWith(Promise.scala:36)
        at scala.concurrent.impl.Promise.transformWith$(Promise.scala:34)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transformWith(Promise.scala:375)
        at scala.concurrent.Future.flatMap(Future.scala:301)
        at scala.concurrent.Future.flatMap$(Future.scala:301)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.flatMap(Promise.scala:375)
        at cats.instances.FutureInstances$$anon$1.flatMap(future.scala:13)
        at cats.instances.FutureInstances$$anon$1.flatMap(future.scala:10)
        at io.iteratee.Enumeratee$$anon$25.apply(Enumeratee.scala:11)
        at io.iteratee.Enumerator.intoStep(Enumerator.scala:15)
        at io.iteratee.Enumerator.$anonfun$into$1(Enumerator.scala:17)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I am able to run simple enumerators like `iterate(1)(_ + 1)` with future module. But all of the file enumerators that I tried fail with NPE when ran with future module. 

NPE is from `executor.prepare()`. Execution context in the future module is null?

**Comment by travisbrown** [comment]
Ugh, thanks for the report. I'm taking a look now.

**Comment by travisbrown** [comment]
Yep, you're right. I know the `future` module doesn't get used much but I thought our tests were better than this.

**Comment by travisbrown** [comment]
The fix is pretty straightforward (one `def`-to-`val`), but I'd like to get tests in place to verify that something like this doesn't happen again, and all other things being equal I'd prefer to wait for Cats 0.9 to publish a new version. Do you need this right away, @2m?

**Comment by 2m** [comment]
Thanks for fixing this so quickly. I am fine with whenever the new version gets released.
